# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 16:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('content', models.TextField(verbose_name='content')),
                ('draft', models.BooleanField(default=False, verbose_name='is draft?')),
                ('publish_date', models.DateTimeField(blank=True, null=True, verbose_name='publish date')),
                ('change_date', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', verbose_name='image', width_field='width_field')),
                ('width_field', models.IntegerField(default=0, null=True)),
                ('height_field', models.IntegerField(default=0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
        ),
    ]
