# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20170129_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', verbose_name='image', width_field='width_field'),
        ),
    ]
